### ISSUE TITLE
npm install fails EINTEGRITY

### ISSUE THREAD

**Issue by Positive07** [TannerRogalsky/love.js#53]
Tried installing love.js node package, with `npm install love.js -g` but it failed due to integrity checks
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'love.js',
1 verbose cli   '-g' ]
2 info using npm@5.0.4
3 info using node@v8.0.0
4 verbose npm-session cf2e20db927b6c72
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/love.js 2059ms (from cache)
8 silly pacote tag manifest for love.js@latest fetched in 2107ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule love.js@0.11.0-rc2 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/commander 465ms (from cache)
15 silly pacote range manifest for commander@^2.9.0 fetched in 469ms
16 silly resolveWithNewModule commander@2.11.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/fs-extra 756ms (from cache)
18 silly pacote range manifest for fs-extra@^3.0.1 fetched in 761ms
19 silly resolveWithNewModule fs-extra@3.0.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/mustache 780ms (from cache)
21 silly pacote range manifest for mustache@^2.3.0 fetched in 782ms
22 silly resolveWithNewModule mustache@2.3.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/klaw-sync 875ms (from cache)
24 silly pacote range manifest for klaw-sync@^2.1.0 fetched in 877ms
25 silly resolveWithNewModule klaw-sync@2.1.0 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/uuid 1484ms (from cache)
27 silly pacote range manifest for uuid@^3.0.1 fetched in 1485ms
28 silly resolveWithNewModule uuid@3.1.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/graceful-fs 327ms (from cache)
30 silly pacote range manifest for graceful-fs@^4.1.2 fetched in 334ms
31 silly resolveWithNewModule graceful-fs@4.1.11 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/universalify 336ms (from cache)
33 silly pacote range manifest for universalify@^0.1.0 fetched in 338ms
34 silly resolveWithNewModule universalify@0.1.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/jsonfile 342ms (from cache)
36 silly pacote range manifest for jsonfile@^3.0.0 fetched in 344ms
37 silly resolveWithNewModule jsonfile@3.0.0 checking installable status
38 silly currentTree nodejs
39 silly idealTree nodejs
39 silly idealTree `-- love.js@0.11.0-rc2
39 silly idealTree   +-- commander@2.11.0
39 silly idealTree   +-- fs-extra@3.0.1
39 silly idealTree   +-- graceful-fs@4.1.11
39 silly idealTree   +-- jsonfile@3.0.0
39 silly idealTree   +-- klaw-sync@2.1.0
39 silly idealTree   +-- mustache@2.3.0
39 silly idealTree   +-- universalify@0.1.0
39 silly idealTree   `-- uuid@3.1.0
40 silly install generateActionsToTake
41 silly diffTrees action count 9
42 silly diffTrees add graceful-fs@4.1.11
43 silly diffTrees add jsonfile@3.0.0
44 silly diffTrees add universalify@0.1.0
45 silly diffTrees add commander@2.11.0
46 silly diffTrees add fs-extra@3.0.1
47 silly diffTrees add klaw-sync@2.1.0
48 silly diffTrees add mustache@2.3.0
49 silly diffTrees add uuid@3.1.0
50 silly diffTrees add love.js@0.11.0-rc2
51 silly decomposeActions action count 72
52 silly decomposeActions fetch graceful-fs@4.1.11
53 silly decomposeActions extract graceful-fs@4.1.11
54 silly decomposeActions preinstall graceful-fs@4.1.11
55 silly decomposeActions build graceful-fs@4.1.11
56 silly decomposeActions install graceful-fs@4.1.11
57 silly decomposeActions postinstall graceful-fs@4.1.11
58 silly decomposeActions finalize graceful-fs@4.1.11
59 silly decomposeActions refresh-package-json graceful-fs@4.1.11
60 silly decomposeActions fetch jsonfile@3.0.0
61 silly decomposeActions extract jsonfile@3.0.0
62 silly decomposeActions preinstall jsonfile@3.0.0
63 silly decomposeActions build jsonfile@3.0.0
64 silly decomposeActions install jsonfile@3.0.0
65 silly decomposeActions postinstall jsonfile@3.0.0
66 silly decomposeActions finalize jsonfile@3.0.0
67 silly decomposeActions refresh-package-json jsonfile@3.0.0
68 silly decomposeActions fetch universalify@0.1.0
69 silly decomposeActions extract universalify@0.1.0
70 silly decomposeActions preinstall universalify@0.1.0
71 silly decomposeActions build universalify@0.1.0
72 silly decomposeActions install universalify@0.1.0
73 silly decomposeActions postinstall universalify@0.1.0
74 silly decomposeActions finalize universalify@0.1.0
75 silly decomposeActions refresh-package-json universalify@0.1.0
76 silly decomposeActions fetch commander@2.11.0
77 silly decomposeActions extract commander@2.11.0
78 silly decomposeActions preinstall commander@2.11.0
79 silly decomposeActions build commander@2.11.0
80 silly decomposeActions install commander@2.11.0
81 silly decomposeActions postinstall commander@2.11.0
82 silly decomposeActions finalize commander@2.11.0
83 silly decomposeActions refresh-package-json commander@2.11.0
84 silly decomposeActions fetch fs-extra@3.0.1
85 silly decomposeActions extract fs-extra@3.0.1
86 silly decomposeActions preinstall fs-extra@3.0.1
87 silly decomposeActions build fs-extra@3.0.1
88 silly decomposeActions install fs-extra@3.0.1
89 silly decomposeActions postinstall fs-extra@3.0.1
90 silly decomposeActions finalize fs-extra@3.0.1
91 silly decomposeActions refresh-package-json fs-extra@3.0.1
92 silly decomposeActions fetch klaw-sync@2.1.0
93 silly decomposeActions extract klaw-sync@2.1.0
94 silly decomposeActions preinstall klaw-sync@2.1.0
95 silly decomposeActions build klaw-sync@2.1.0
96 silly decomposeActions install klaw-sync@2.1.0
97 silly decomposeActions postinstall klaw-sync@2.1.0
98 silly decomposeActions finalize klaw-sync@2.1.0
99 silly decomposeActions refresh-package-json klaw-sync@2.1.0
100 silly decomposeActions fetch mustache@2.3.0
101 silly decomposeActions extract mustache@2.3.0
102 silly decomposeActions preinstall mustache@2.3.0
103 silly decomposeActions build mustache@2.3.0
104 silly decomposeActions install mustache@2.3.0
105 silly decomposeActions postinstall mustache@2.3.0
106 silly decomposeActions finalize mustache@2.3.0
107 silly decomposeActions refresh-package-json mustache@2.3.0
108 silly decomposeActions fetch uuid@3.1.0
109 silly decomposeActions extract uuid@3.1.0
110 silly decomposeActions preinstall uuid@3.1.0
111 silly decomposeActions build uuid@3.1.0
112 silly decomposeActions install uuid@3.1.0
113 silly decomposeActions postinstall uuid@3.1.0
114 silly decomposeActions finalize uuid@3.1.0
115 silly decomposeActions refresh-package-json uuid@3.1.0
116 silly decomposeActions fetch love.js@0.11.0-rc2
117 silly decomposeActions extract love.js@0.11.0-rc2
118 silly decomposeActions preinstall love.js@0.11.0-rc2
119 silly decomposeActions build love.js@0.11.0-rc2
120 silly decomposeActions install love.js@0.11.0-rc2
121 silly decomposeActions postinstall love.js@0.11.0-rc2
122 silly decomposeActions finalize love.js@0.11.0-rc2
123 silly decomposeActions refresh-package-json love.js@0.11.0-rc2
124 silly install executeActions
125 silly doSerial global-install 72
126 verbose correctMkdir C:\Users\nano0\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
127 verbose lock using C:\Users\nano0\AppData\Roaming\npm-cache\_locks\staging-dfd8fbf9c1feea0f.lock for C:\Program Files\nodejs\node_modules\.staging
128 silly doParallel extract 72
129 silly extract graceful-fs@4.1.11
130 silly pacote trying graceful-fs@https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz by hash: sha1-Dovf5NHduIVNZOBOp8AOKgJuVlg=
131 silly extract jsonfile@3.0.0
132 silly pacote trying jsonfile@https://registry.npmjs.org/jsonfile/-/jsonfile-3.0.0.tgz by hash: sha1-kufHRE5f/V+jLmqa6LhQNN+DR9A=
133 silly extract universalify@0.1.0
134 silly pacote trying universalify@https://registry.npmjs.org/universalify/-/universalify-0.1.0.tgz by hash: sha1-nrHEZR3rzGcMyU8adXYjMruWd3g=
135 silly extract commander@2.11.0
136 silly pacote trying commander@https://registry.npmjs.org/commander/-/commander-2.11.0.tgz by hash: sha512-b0553uYA5YAEGgyYIGYROzKQ7X5RAqedkfjiZxwi0kL1g3bOaBNNZfYkzt/CL0umgD5wc9Jec2FbB98CjkMRvQ==
137 silly extract fs-extra@3.0.1
138 silly pacote trying fs-extra@https://registry.npmjs.org/fs-extra/-/fs-extra-3.0.1.tgz by hash: sha1-N5TzeMWLNC6n27sjCVEJxLO2IpE=
139 silly extract klaw-sync@2.1.0
140 silly pacote trying klaw-sync@https://registry.npmjs.org/klaw-sync/-/klaw-sync-2.1.0.tgz by hash: sha1-PTvNhgDnv971MjHHOf8FOu1WDkQ=
141 silly extract mustache@2.3.0
142 silly pacote trying mustache@https://registry.npmjs.org/mustache/-/mustache-2.3.0.tgz by hash: sha1-QCj3d4sXcIpImTCm5SrDvKDaQdA=
143 silly extract uuid@3.1.0
144 silly pacote trying uuid@https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz by hash: sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g==
145 silly extract love.js@0.11.0-rc2
146 silly pacote trying love.js@https://registry.npmjs.org/love.js/-/love.js-0.11.0-rc2.tgz by hash: sha1-ky9QOvGf+uAT5+WpT3F+03OTUvQ=
147 silly pacote data for sha1-ky9QOvGf+uAT5+WpT3F+03OTUvQ= not present. Using manifest.
148 silly pacote universalify@https://registry.npmjs.org/universalify/-/universalify-0.1.0.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\universalify-269ed4e8 by content address 90ms
149 silly pacote klaw-sync@https://registry.npmjs.org/klaw-sync/-/klaw-sync-2.1.0.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\klaw-sync-bab331b3 by content address 101ms
150 silly pacote commander@https://registry.npmjs.org/commander/-/commander-2.11.0.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\commander-a40d8efc by content address 107ms
151 silly pacote jsonfile@https://registry.npmjs.org/jsonfile/-/jsonfile-3.0.0.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\jsonfile-ffa9e856 by content address 118ms
152 silly pacote graceful-fs@https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\graceful-fs-95606d5d by content address 132ms
153 silly pacote uuid@https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\uuid-6936b99e by content address 161ms
154 silly pacote mustache@https://registry.npmjs.org/mustache/-/mustache-2.3.0.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\mustache-62300005 by content address 165ms
155 silly pacote fs-extra@https://registry.npmjs.org/fs-extra/-/fs-extra-3.0.1.tgz extracted to C:\Program Files\nodejs\node_modules\.staging\fs-extra-e44b534e by content address 268ms
156 verbose unlock done using C:\Users\nano0\AppData\Roaming\npm-cache\_locks\staging-dfd8fbf9c1feea0f.lock for C:\Program Files\nodejs\node_modules\.staging
157 verbose stack Error: sha1-ky9QOvGf+uAT5+WpT3F+03OTUvQ= integrity checksum failed when using sha1: wanted sha1-ky9QOvGf+uAT5+WpT3F+03OTUvQ= but got sha1-bsquo3vpaEGPIIAkBotcbOdA0PA=. (3964553 bytes)
157 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
157 verbose stack     at emitNone (events.js:110:20)
157 verbose stack     at Transform.emit (events.js:207:7)
157 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
157 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
157 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
158 verbose cwd C:\WINDOWS\system32
159 verbose Windows_NT 10.0.15063
160 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "love.js" "-g"
161 verbose node v8.0.0
162 verbose npm  v5.0.4
163 error code EINTEGRITY
164 error sha1-ky9QOvGf+uAT5+WpT3F+03OTUvQ= integrity checksum failed when using sha1: wanted sha1-ky9QOvGf+uAT5+WpT3F+03OTUvQ= but got sha1-bsquo3vpaEGPIIAkBotcbOdA0PA=. (3964553 bytes)
165 verbose exit [ 1, true ]
```
I suppose this has to do with my internet connection, the file being too big and npm having a bad https request system which drops packages and stuff...

Electron is a package that I have installed successfully many times and is way bigger that love.js so checking how they do it may be a good alternative?

**Comment by Positive07** [comment]
On another note, the name love.js is not Windows friendly, I can't run this package at all since it's looking for a JS file instead... I recommend you rename it to lovejs or something else...

**Comment by TannerRogalsky** [comment]
I should remove the debug build from the npm package to make it necessary. It don't think it should really adds anything.

As for the windows issue... you sure? On *nix platforms it symlinks the defined entry point to a file named `love.js` in a standard binary folder (`/usr/local/bin` for me). What does it even do on windows?

**Comment by Positive07** [comment]
Sorry but since I installed in a weird way (grabbed this source code, and run `npm install -g` in it) I cannot say that it's this package fault.

First was using PowerShell, second the install command created two files, a no extension bash file and a `.cmd` file for bat, for normal stuff the `.cmd` would be used in PowerShell, but since the package is called love.js the files are called `love.js` and `love.js.cmd` so PowerShell prefers to run the former with Windows JScript which we all know sucks and fails because it's actually an sh script.

I renamed the files to `lovejs` and `lovejs.cmd` and it works with those aliases now.

On another note I'm having problems with packaging folders (No main.lua found)

**Comment by TannerRogalsky** [comment]
I've uploaded a new version: `0.11.0-rc3`

It's no different except that it doesn't include the debug build so it should be significantly smaller. Perhaps that will help?

**Comment by Positive07** [comment]
I'm testing 0.11.0-rc2 and I can't get anything on screen, I downloaded the latest build of 0.11.0 and it works fine. I'll give you the .love file (which is a modified version of something I found in the forums)

[MINESWEEP.zip](https://github.com/TannerRogalsky/love.js/files/1123306/MINESWEEP.zip) rename it to .love because GitHub.

I'll test with 0.11.0-rc3 once it installs

**Comment by Positive07** [comment]
Update: You'll need to rename the package if you want it to work on Windows because unfortunately it can be executed:

![captura de pantalla 2017-07-04 23 02 40](https://user-images.githubusercontent.com/1095969/27846338-ea0cf490-610c-11e7-92f9-ff76194e617f.png)

**Comment by TannerRogalsky** [comment]
Huh, that's annoying.

**Comment by TannerRogalsky** [comment]
The game you posted works great for me in Chrome Canary and Firefox Nightly under OSX.

**Comment by Positive07** [comment]
I'm running Chrome Beta in Windows 10 with no luck, could you upload the `game.data` file or the entire release build so I can see if I screwed something up or it's just my browser?

**Comment by TannerRogalsky** [comment]
It's your browser. You need Chrome Canary or Firefox Nightly.

**Comment by Positive07** [comment]
Oh will do that... any reason why it doesn't work with beta anymore? I mean, the 0.10.2 version does I believe

**Comment by TannerRogalsky** [comment]
Yeah, thread support. Support is poor right now but it will get better.

**Comment by Positive07** [comment]
Right, I see. Well I'll download either later and test, if I also want to test the older version, can I just change the release folder of the npm love.js package with the older one?

Also I would love you if you can rename love.js npm package to lovejs or I don't know love.js-build something that _Stupid Windows_ doesn't think it's a file extension
